---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-app
  namespace: nodejs
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: "varunpasumarthi/nodejsapp:latest"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: nodejs
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports:
  -
    targetPort: 3000
    port: 80


              
